### ISSUE TITLE
Add p6spy dependency incorporation

### ISSUE THREAD

**Issue by manueljordan** [spring-io/platform#153]
I think would be very valuable add the following how a dependency

[p6spy](https://github.com/p6spy/p6spy)

In the same way we have JUnit, why not p6spy?

Thanks.

**Comment by wilkinsona** [comment]
The general rule for including a dependency in the Platform is that it's used by one or more Spring projects. For example, the Platform contains JUnit because Spring Framework's testing support is built on JUnit. None of the Spring projects in the Platform use p6spy so it's not appropriate to include it in the Platform. Sorry, but we have to draw the line somewhere.

**Comment by manueljordan** [comment]
No worries, thanks by the explanation. But such rule is indicated or mentioned in the reference documentation?

**Comment by wilkinsona** [comment]
Not yet. See #61.

**Comment by manueljordan** [comment]
I see, thank you.
