### ISSUE TITLE
Why does spring.io platform depend on spring-boot-dependencies and not the other way around?

### ISSUE THREAD

**Issue by rdehuyss** [spring-io/platform#170]
> **Start rant**
> We just spend a full afternoon investigatin why we had a version clash with jersey. We need to depend  on jersey-2.15 or higher due to a performance bug in jersey-2.14 and lower. 

> Since there is **no reference in the spring.io platform documentation about jersey**, we include both the spring.io bom (io.spring.platform:platform-bom:1.1.0.RELEASE) and the jersey-bom (org.glassfish.jersey:jersey-bom:2.15). 

> We had all kind of strange errors like at runtime (nosuchmethod error). 

> After a 3-hour debugging session we saw that we had the wrong dependencies for jersey (2.13 instead of 2.17) and further investigation showed that the spring.io bom depends on the spring-boot-dependencies pom (via parent pom) and in there the jersey version was stated as 2.13.
> **End rant**

**Three questions/bugs (if you want seperate issues, just shout):**
* Why does spring.io platform depend on spring-boot-dependencies and not the other way around?
* Please specify all the dependencies that are inherited via the spring-boot-dependencies also in the spring.io documentation
* There are version clashes between spring.io platform and spring-boot-dependencies. Could you fix these and make sure that the latest (the ones specified in spring-boot-dependencies) are used. Examples are:
  * tomcat-embed
  * flyway-core
  * ...
* Could you upgrade jersey as jersey-client has performance bugs which are fixed in versions higher or equal to 2.15.

Thanks in advance,
Ronald

P.s.: sorry about the rant but we lost 1.5 mandays in total on this...

**Comment by wilkinsona** [comment]
>  there is no reference in the spring.io platform documentation about jersey

The [reference documentation](http://docs.spring.io/platform/docs/1.1.1.RELEASE/reference/htmlsingle/) contains no fewer than 11 occurrences of "jersey".

> Why does spring.io platform depend on spring-boot-dependencies and not the other way around?

Spring Boot is, by design, part of the Spring IO Platform. Inverting the dependency so that `spring-boot-dependencies` depends on the Platform would require the Platform to be part of Spring Boot.

> Please specify all the dependencies that are inherited via the spring-boot-dependencies also in the spring.io documentation

They're already listed. 10 of the 11 aforementioned occurrences of "jersey" are for dependency management of Jersey modules that has been inherited from Spring Boot. The 11th if for `spring-boot-starter-jersey`, also inherited from Spring Boot.

> There are version clashes between spring.io platform and spring-boot-dependencies. Could you fix these and make sure that the latest (the ones specified in spring-boot-dependencies) are used. 

Generally speaking, there's nothing to be done here. The Platform uses the dependency management from the version of Spring Boot that it extends. For example, the current version of the Platform (1.1.1.RELEASE) extends Spring Boot 1.2.1.RELEASE. Spring Boot 1.2.1.RELEASE provides dependency management for Flyway 3.0 so the current version of the Platform also provides dependency management for Flyway 3.0. This will change in Spring IO Platform 1.1.2.RELEASE when it upgrade to Spring Boot 1.2.3.RELEASE (see #165). We can safely make this change as Flyway 3.1 is backwards compatible with 3.0.

A notable exception to this is with Tomcat (and Jetty). Spring IO Platform takes a more conservative approach to backwards compatibility than Spring Boot does. To this end, Spring IO Platform 1.1 overrides Spring Boot's dependency management so that it uses Tomcat 7 rather than Tomcat 8. This is due to breaking changes between Tomcat 7 and Tomcat 8.

> Could you upgrade jersey as jersey-client has performance bugs which are fixed in versions higher or equal to 2.15.

Jersey's dependency management is inherited from Spring Boot, so this request should be made there. Please [open an issue](https://github.com/spring-projects/spring-boot/issues/new). In the meantime, you can override the `jersey.version` property to use your preferred version.

**Comment by rdehuyss** [comment]
Hi Andy,

my mistake - I was looking to the documentation of io.spring.platform:platform-bom:1.0.1.RELEASE where Jersey was not included yet. I assume it was the heat of the moment. My sincerest apologies for the rant.

Kind regards,
Ronald
