### ISSUE TITLE
Provide a Description about Files and Folders

### ISSUE THREAD

**Issue by lazaridis-com** [spring-io/platform#195]
The source-tree does currently not contain any description about it's contents.

Either the root README should mention the contents of the folders, or the folders should contain a README with a quick description.

(This would help code-level newcomers to get a quick overview)

Additionally, documentation on how this **sources** work should be provided, how the bom is generated, etc.

**Comment by wilkinsona** [comment]
The project is a standard multi-module Maven build and each pom already contains a description for the module. The README that you've proposed would simply be repeating existing information.

>  documentation on how this sources work should be provided

Sorry, I don't understand what you mean.

> how the bom is generated

The bom isn't generated. It's defined in platform-bom/pom.xml

**Comment by lazaridis-com** [comment]
Ok, I am familiar with Maven, so I can look-up some information under the `<project><description>` tag.

* platform-bom, ok
* platform-test, ok
* platform: why is this named "platform" and not "platform-doc" (or similar)?
* scripts: what are those scripts for?
* platform-definition.yaml: what is this file for?

**Comment by lazaridis-com** [comment]
Here an **example** for the root README, which would explain to a code-level newcomers (like me) what's going on (without the need for them to do research).

I can send a PR in (would just need the answers to the questions, in order to know what to write)

## Sources

The project is mostly organized as a standard maven multi-module project, with a few exceptions.

You can lookup the description of each module within the `<project><description>` section of it's pom.xml.

The `scripts` folder is used for ?

The `platform-definition.yaml` contains ? for use within ?

### Modifying

Note that the result of this project is **manually defined** within platform-bom/pom.xml (bom = Bill of Materials).

If for any reasons you need an altered version, you would simply modify the `platform-bom/pom.xml` and do the usual `mvn install` thus it becomes available within your local repo.

**Comment by wilkinsona** [comment]
I appreciate your interest here, but I won't be changing the README in the way that you suggest as it's not how a want the README to be used.

I do, however, have some plans to update the repository's wiki with details of how the platform is built (#200). I may also make some updates to the scripts with usage information as part of that work.

**Comment by lazaridis-com** [comment]
>it's not how I want

`Explaining the Sources` is standard usage of a README for source-code, and you (a core-developer) should really not be the metric for the quality of this README, as it adresses code-level newcomers. In other words: newcomers must be happy with the README, not you (or other core-developers).

As for the wiki, source-code documentatioin should be of course **close** to the source, or **within** the source, and not spreaded around in wiki's etc.

In any way, do it as you like, just can you please provide me with an general quick answer to this here:

platform: why is this named "platform" and not "platform-doc" (or similar)?
scripts: what are those scripts for?
platform-definition.yaml: what is this file for?

**Comment by wilkinsona** [comment]
Contrary to what you may believe, there's no standard for how a README should be used and it's entirely up to the maintainers of a project to decide how to use the README. For the Platform, along with many other Spring projects, we have decided to use the README to tell people what the project is and to provide information, or links to information, about how it can be used.

The Platform is open source, and we welcome constructive contributions from anyone. However, telling people what to do because the status quo doesn't meet your expectations isn't constructive and is more likely to offend than to lead to anything being done.

Now, to answer your questions:

> platform: why is this named "platform" and not "platform-doc" (or similar)?

The location to which the documentation is published is determined by the name of the module. We want the location to be `platform` so that's the name of the module.

> scripts: what are those scripts for?

They're used as part of updating, building, and releasing the platform.

 - `addLocalMavenRepository.gradle` a Gradle init script to add the local Maven repository to a project
 - `buildPlatform.groovy` - used to build the projects in the Platform using the versions defined by the Platform
 - `dependencyVersions.groovy` - Checks the Platform bom against Maven central and lists any newer dependency versions
 - `findDuplicates.groovy` - Identifies dependencies that are declared in Spring Boot and in the Platform and that, therefore, should be removed from the Platform

> platform-definition.yaml: what is this file for?

It defines all of the projects and their modules that are part of the Platform. It's used by the `buildPlatform.groovy` script to determine what projects to build and how to build them. It's also used by the tests in `platform-tests` to verify the contents of the bom.

**Comment by lazaridis-com** [comment]
> Contrary to what you may believe, there's no standard for how a README should be used and it's entirely up to the maintainers of a project to decide how to use the README.

Is this so? One never stops to learn!

>the status quo doesn't meet your expectations

**My** expectations?

Please, the status quo doesn't meet the given, decades old IT standard (or quasi-standard, or requirement) that source-code needs to be documented close to the source. This is really nothing special.

My only (natural) expectation was that this IT standard (or quasi-standard, or requirement) is met by the source-code of the spring-platform. I'm just stating the obvious, and if anyone feels offended by this, then it's his very personal problem.

Now to your answers:

I get a better picture now, but be aware that I'm still not able to fully understand the sources, in a way that I can fully handle them (build, modify etc.).

So, I guess I'll await the wiki update you announced (#200).
