### ISSUE TITLE
Why is JUnit downgraded to 4.11?

### ISSUE THREAD

**Issue by openwms** [spring-io/platform#204]
Took me a while to find out that JUnit 4.11 is on my projects classpath instead of 4.12 and for that reason my unit tests are not executed anymore. I'm using the JUnit `@Category` annotation on abstract super classes for tests. Inheritance of this annotation to test classes works since 4.12 of JUnit. Is there a reason for the downgrade? Because `spring-boot-dependencies` project defines a version of 4.12.

**Comment by wilkinsona** [comment]
Regrettably, it's downgraded so that it's compatible with Powermock. Powermock depends on JUnit internals that changed between 4.11 and 4.12 (see https://github.com/spring-io/platform/issues/113). If you're not using Powermock, and I would strongly recommend that you don't, you can safely override the version back to 4.12 again.

**Comment by openwms** [comment]
Okay, thanks for clarification. I don't need to use Powermock, hence it's okay for me to override. Would it make sense to comment such downgrades in the pom.xml?
<-- Pinned to 4.11 to be compatible with the latest version of Powermock -->
