### ISSUE TITLE
Using Jersey pulls two different versions of Jackson libraries as transitive dependencies

### ISSUE THREAD

**Issue by troinine** [spring-io/platform#305]
By using the following dependencies from Spring IO Platform 2.0.0.RELEASE 

- spring.framework.boot:spring-boot-starter-web
- spring.framework.boot:spring-boot-starter-jersey

We get two flavours of Jackson libraries into our application

- com.fasterxml.jackson.core:jackson-databind:2.6.3
- com.fasterxml.jackson.core:jackson-core:2.6.3
- com.fasterxml.jackson.core:jackson-annotations:2.6.3
- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:**2.5.4**
- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:**2.5.4**
- com.fasterxml.jackson.module:jackson-module-jab-annotations:**2.5.4**

At first, this does not seem like a problem as they should be ABI compatible. However, we have managed to get a dependency issue in a maven multi-module project in which we use 2.6.3 version (the same as Spring IO platform declares) of ```jackson-jaxrs-json-provider```. Running a Spring Boot app with a Jersey servlet fails with the following stack trace when POSTing an entity to a Jersey endpoint.

```
015-12-20 09:53:57,455 ERROR - [jerseyServlet] - Servlet.service() for servlet [jerseyServlet] in context with path [] threw exception [org.glassfish.jersey.server.ContainerException: java.lang.NoSuchMethodError: com.fasterxml.jackson.jaxrs.cfg.EndpointConfigBase.<init>(Lcom/fasterxml/jackson/databind/cfg/MapperConfig;)V] with root cause 
java.lang.NoSuchMethodError: com.fasterxml.jackson.jaxrs.cfg.EndpointConfigBase.<init>(Lcom/fasterxml/jackson/databind/cfg/MapperConfig;)V
	at com.fasterxml.jackson.jaxrs.json.JsonEndpointConfig.<init>(JsonEndpointConfig.java:30) ~[jackson-jaxrs-json-provider-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.jaxrs.json.JsonEndpointConfig.forReading(JsonEndpointConfig.java:36) ~[jackson-jaxrs-json-provider-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider._configForReading(JacksonJsonProvider.java:217) ~[jackson-jaxrs-json-provider-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider._configForReading(JacksonJsonProvider.java:45) ~[jackson-jaxrs-json-provider-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.jaxrs.base.ProviderBase._configForReading(ProviderBase.java:467) ~[jackson-jaxrs-base-2.5.4.jar:2.5.4]
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:775) ~[jackson-jaxrs-base-2.5.4.jar:2.5.4]
```

Looks like ```com.fasterxml.jackson.jaxrs.json.JsonEndpointConfig``` from 2.6.3 is not compatible with ```com.fasterxml.jackson.jaxrs.cfg.EndpointConfigBase``` 2.5.4 as there is new constructor declared in 2.6.3 version of the lib

Spring Boot Starter Jersey pulls in ```org.glassfish.jersey.core:jersey-server:jar:2.22.1``` which eventually pulls in ```org.glassfish.jersey.media:jersey-media-json-jackson:jar:2.22.1``` which then pulls the older versions of Jackson JAX-RS libraries.

We have worked around this by declaring ```com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:2.6.3``` and ```com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:2.6.3``` in our own Maven Bill of Materials but I'm just wondering that would it make sense to include these as part of the Spring IO Platform dependency management to avoid the potential binary incompatibility issues when using Jackson libraries? 

Of course in theory, this could cause issues with Jersey as its 2.22.1 relies on 2.5.4 versions of Jackson JAX-RS libs but so far, I haven't seen any issues in our integration tests when using version 2.6.3 from all Jackson dependencies and with Jersey 2.22.1.

Sadly I wasn't able to reproduce this issue with an isolated test project yet which you could use to verify this. I might try again but looks like I need to dig deeper into the dependency hierarchies.

Also, looks like Spring IO 2.0.1.RELEASE has the same issue but it pulls 2.6.4 versions of the core Jackson libraries.

**Comment by wilkinsona** [comment]
The reason you're seeing different versions of some of the Jackson dependencies is that the Platform doesn't provide dependency management for all of them. Specifically, there's no dependency management for: 

 - `com.fasterxml.jackson.jaxrs:jackson-jaxrs-base`
 - `com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider`
 - `com.fasterxml.jackson.module:jackson-module-jab-annotations`

A list of all of the dependency management that the Platform does provide is [included in the documentation](http://docs.spring.io/platform/docs/current/reference/htmlsingle/).

As things stand, if you want dependency management for these additional Jackson modules then you should declare your own. Assuming that you're using the Platform's bom as your project's parent, I'd recommend using the `jackson.version` property so that the versions are aligned with the version of Jackson in the Platform.

The Platform inherits the dependency management for Jackson from Spring Boot. If you'd like to see dependency management for additional Jackson modules, please [open a Spring Boot issue](https://github.com/spring-projects/spring-boot/issues/new).
