### ISSUE TITLE
[Question] There was MAJOR version change from 1.x to 2.x, where can I find note on that

### ISSUE THREAD

**Issue by paulvi** [spring-io/platform#358]
There was MAJOR version change from 1.x to 2.x, where can I find note on that?

Possible there exists simple tool or approach to compare https://github.com/spring-io/platform/blob/master/platform-bom/pom.xml, but in simple explanation why it is now 2.x ?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it)

**Comment by wilkinsona** [comment]
This sort of question is better suited to Stack Overflow. You can use the `spring-io` tag.

**Comment by paulvi** [comment]
ok

**Comment by wilkinsona** [comment]
This [blog post](https://spring.io/blog/2015/11/18/spring-io-platform-2-0-0-release) may also be of interest.
