### ISSUE TITLE
Update Spring Session Modules

### ISSUE THREAD

**Issue by rwinch** [spring-io/platform#622]
The spring-session module was broken into spring-session-core, spring-session-data-redis, spring-session-data-hazelcast, and spring-session-jdbc. Please update so that `springIoDependencyVersionMappingCheck` will pass again

**Comment by wilkinsona** [comment]
There's a chicken and egg problem here as the Platform cannot provide dependency management for an artifact that doesn't exist. Also, that dependency management is in Boot; the Platform just inherits it. The path of least resistance here is to tweak your CI job so that snapshots can be published without running `springIoDependencyVersionMappingCheck`.

**Comment by rwinch** [comment]
> There's a chicken and egg problem here as the Platform cannot provide dependency management for an artifact that doesn't exist.

Thanks for pointing out that. I have published the artifacts which are available in Spring's Artifactory now https://repo.spring.io/libs-snapshot/org/springframework/session/spring-session-core/
