### ISSUE TITLE
Update Cairo SNAPSHOT to Reactor Bismuth-BUILD-SNAPSHOT

### ISSUE THREAD

**Issue by rwinch** [spring-io/platform#643]
This is necessary so that users can continue running tests to ensure they are platform compliant using the latest reactor bom

**Comment by wilkinsona** [comment]
The Platform's primary concern at the moment is ensuring compatibility for Boot's M4 that's due later this week. Once that's shipped, Boot will move to a more recent Reactor dependency and that Platform will pick up that change.

**Comment by rwinch** [comment]
@wilkinsona Thank you for the reply.

This solution does not seem like a good solution for the platform as a whole. As it stands, running tests against Cairo SNAPSHOT do not instill confidence that a code base is working against the latest SNAPSHOT towards Cairo RELEASE. It really appears to be testing if things work with the next Boot release (which is not what we really want). Could you provide a milestone of Platform (or a different SNAPSHOT) for Boot to use? 

If Cairo SNAPSHOT does not get updated, should I stop testing against Spring IO Platform? What is the recommended approach? It seems to provide little value to test against Spring IO Platform if I'm overriding the dependencies. 

> Once that's shipped, Boot will move to a more recent Reactor dependency and that Platform will pick up that change.

Can we reopen this ticket? Even if the answer is "we won't update until later", I'd love to be able to be notified when reactor is updated and subscribing to an open ticket seems to make sense for such notifications.

Thanks!

**Comment by wilkinsona** [comment]
I understand the problem, but this is the best we can do at the moment with the resources available. This problem's really a one-off as it's a side-effect of us freezing dependencies for Boot M4. We don't have plans to repeat that for M5 and beyond.

> Could you provide a milestone of Platform (or a different SNAPSHOT) for Boot to use?

Boot doesn't use the Platform, it's a subset of the Platform. For better or worse, Boot makes use of the Platform's compatibility testing to ensure that the subset of the Platform that it manages is compatible. We could split the compatibility testing so that some's done in Boot and the rest is done in the Platform but that'd be a fairly significant undertaking and there simply isn't time to tackle it at the moment.

> What is the recommended approach? It seems to provide little value to test against Spring IO Platform if I'm overriding the dependencies

Unfortunately, I don't think there's a simple answer here. I can think of a few possible solutions, but they all require more effort than I can justify for a problem that will solve itself in the next few days. If the compatibility checks are failing, you'd probably be best temporarily disabling them or overriding a few versions.

> Can we reopen this ticket?

Reopening the ticket won't get you what you want as there won't be a change made to the Platform that would then close it. The Platform's already building against Boot snapshots so as soon as Boot moves to a newer version of Reactor, the Platform will pick that up.

**Comment by rwinch** [comment]
> Reopening the ticket won't get you what you want as there won't be a change made to the Platform that would then close it. The Platform's already building against Boot snapshots so as soon as Boot moves to a newer version of Reactor, the Platform will pick that up.

@wilkinsona Is there another ticket I should follow or create?

**Comment by wilkinsona** [comment]
There is now: https://github.com/spring-projects/spring-boot/issues/10121. As part of moving towards Bismuth RC1 we'll start building against snapshots soon.
