### ISSUE TITLE
Configuration of gmavenplus-plugin cannot be changed

### ISSUE THREAD

**Issue by zarebski-m** [spring-io/platform#740]
I am using Spring Platform Brussels-SR7, but I've seen the same configuration in Athens.

Platform BOM declares gmavenplus-plugin in hardcoded version 1.1, adds dependency on groovy-all:2.3.0 (hardcoded; why not take `${groovy.version}`?) and configures plugin as non-overridable (`<inherited>false</inherited>`). Therefore it is not possible to configure gmavenplus-plugin in pluginManagement section of POM which uses Platform BOM as parent. Plugin needs to be be fully configured in every POM that uses it.

Actually all of the three plugins declared in Platform BOM declare `<inherited>false</inherited>`. What's the reason behind that and could it maybe be changed?

**Comment by wilkinsona** [comment]
> Actually all of the three plugins declared in Platform BOM declare <inherited>false</inherited>. What's the reason behind that and could it maybe be changed?

The intent was to prevent those plugins from being inherited by projects that use `platform-bom` as their parent. Those plugins are only used as part of the Platform's build process. Child projects should be free to not use those plugins or to configure those plugins as needed.

`<inherited>false</inherited>` has been in the Platform's bom for a long time and I believe it worked as I have described above when it was first added. However, it doesn't appear to work now with Maven 3.5.3, not fully at least. It appears that disabling inheritance prevents the executions from being inherited, but does not prevent the declaration of the plugin itself from being inherited. I wonder if it's always been like that and is intentional, or if that's a bug in Maven? Either way, the bom probably needs to change somehow as relying on a fix in Maven doesn't feel like a realistic solution.

**Comment by wilkinsona** [comment]
I've fixed this in master (Cairo) where the platform-bom.properties artifact is no longer needed. An equivalent change isn't appropriate for Brussels and I am struggling to think of one that is appropriate and will still fix the problem. Unless someone has a moment of inspiration, we may have to live with this in Brussels.

**Comment by zarebski-m** [comment]
I've done some digging and you are right, it looks like a Maven bug. I've reported it here: https://issues.apache.org/jira/browse/MNG-6373 – but I don't hope it would be fixed anytime soon, if ever.

Regarding Brussels: wouldn't it be possible to define those plugins' versions as properties that could be overriden downstream, and use `${groovy.version}` in gmavenplus-plugin dependency? I realize that's not a proper solution but it would add at least a bit of flexibility.

**Comment by wilkinsona** [comment]
Thanks for raising the Maven issue. I'm watching it.

I had hoped to find a way to avoid the plugins appearing in the child pom at all. If using properties for the version of the GMaven+ plugin and its Groovy dependency meets your needs then we can certainly do that.
